[workspace]
members = ["./", "celery-codegen"]

[package]
name = "celery"
version = "0.4.0-rc1"
authors = ["epwalsh <epwalsh10@gmail.com>"]
edition = "2018"
keywords = ["celery", "amqp", "rabbitmq", "background-jobs"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/rusty-celery/rusty-celery"
homepage = "https://github.com/rusty-celery/rusty-celery"
description = "Rust implementation of Celery"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "celery"
path = "src/lib.rs"

[[example]]
name = "celery_app"

[dependencies]
chrono = "0.4"
tokio = { version = "0.2.13", features = ["full"]}
serde = { version = "1.0", features = ["derive"]}
serde_json = { version = "1.0", optional = true }
rmp-serde = { version = "0.14", optional = true }
rmpv = { version = "0.4.5", optional = true, features = ["with-serde"] }
serde_yaml = { version = "0.8", optional = true }
serde-pickle = { version = "0.6", optional = true }
failure = "0.1.7"
async-trait = "0.1"
lapin = { version = "=1.2.1" }
amq-protocol = "=6.0.0-rc12"
log = "0.4"
futures = { version = "0.3", features = ["async-await"] }
uuid = { version = "0.8", features = ["v4"]}
rand = "0.7"
celery-codegen = { version = "0.4.0-rc1", path = "./celery-codegen", optional = true }
once_cell = { version = "1.3.1", optional = true }
globset = "0.4"
# This is only used by amqp-protocol. We need to pin to this version to avoid a compilation error
# where building on nighty Rust.
cookie-factory = "0.3.1"
hostname = "0.3.0"

[dev-dependencies]
env_logger = "0.7"
exitfailure = "0.5.1"
structopt = "0.3"

[features]
default = ["codegen", "format-json", "format-rmp", "format-yaml", "format-pickle"]
codegen = ["celery-codegen", "once_cell"]
format-json = ["serde_json"]
format-rmp = ["rmp-serde", "rmpv"]
format-yaml = ["serde_yaml"]
format-pickle = ["serde-pickle"]